# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Graffiti' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Graffiti

  target 'Graffiti-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GraffitiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

pod 'RadarSDK', '~> 2.1.0'
